name: ci-audit-agent

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
      - 'qa'
      - 'main'
    paths:
      - .github/workflows/audit-agent.yml
      - 'audit-agent/**'
env:
  BRANCH_NAME: ${{github.ref_name}}
 
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
              
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/${{pom.xml}}') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Publish package
        run: cd audit-agent && mvn --batch-mode -f pom.xml -Denv=$BRANCH_NAME deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
