name: ci-share

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
      - 'qa'
env:
  BRANCH_NAME : ${{github.ref_name}}
  POM_NAME : "pom-dev.xml"
  
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Nombre Rama
        run: echo "Nombre de la rama BRANCH_NAME"
        
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom-dev.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Publish to GitHub Packages Apache Maven
        run: cd share && mvn --batch-mode -f pom-dev.xml deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
