name: ci-share

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
      - 'qa'
env:
  BRANCH_NAME: ${{github.ref_name}}
  POM_NAME: ''
  
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set POM name
        run: echo "POM_NAME=pom-$BRANCH_NAME.xml" >> $GITHUB_ENV
        
      - name: Nombre Rama
        run: echo "Nombre de la rama $BRANCH_NAME y nombre del POM $POM_NAME"
        
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/${{POM_NAME}}') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Concat
        run: POM_NAME="${POM_NAME}" >> $GITHUB_ENV
        
      - name: Publish to GitHub Packages Apache Maven
        run: cd share && mvn --batch-mode -f ${{POM_NAME}} deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
