name: ci-share

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
      - 'qa'
      - 'main'
    paths:
      - .github/workflows/share.yml
      - 'share/**'
env:
  BRANCH_NAME: ${{github.ref_name}}
 
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set POM name
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "POM_NAME=pom.xml" >> $GITHUB_ENV
          else
            echo "POM_NAME=pom-$BRANCH_NAME.xml" >> $GITHUB_ENV
          fi
        shell: bash
        
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/${{POM_NAME}}') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Publish package
        run: cd share && mvn --batch-mode -f ${POM_NAME} deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
