name: ci-share

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
      - 'qa'
    paths:
      - .github/workflows/share.yml
      - 'share/**'
env:
  BRANCH_NAME: ${{github.ref_name}}
  JENKINS_URL: ${{ vars.JENKINS_URL }}
  JENKINS_USER: ${{ secrets.JENKINS_USER }}
  JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
  JENKINS_JOB_NAME: ${{ vars.JENKINS_JOB_NAME }}
  
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set POM name
        run: echo "POM_NAME=pom-$BRANCH_NAME.xml" >> $GITHUB_ENV
              
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/${{POM_NAME}}') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Publish package
        run: cd share && mvn --batch-mode -f ${POM_NAME} deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Trigger-jenkins
        run: curl -X POST "${JENKINS_URL}/job/${JENKINS_JOB_NAME}/job/${BRANCH_NAME}/build" --user "${JENKINS_USER}:${JENKINS_API_TOKEN}"
    
